import express from "express";import cors from "cors";import cron from "node-cron";import webpush from "web-push";import fs from "node:fs/promises";import path from "node:path";
const app=express();app.use(cors());app.use(express.json({limit:"50kb"}));
const PORT=process.env.PORT||10000,DATA_DIR=process.env.DATA_DIR||path.resolve("data"),DATA_FILE=path.join(DATA_DIR,"subscriptions.json"),TIMEZONE=process.env.TIMEZONE||"Asia/Kolkata";
const PUBLIC_KEY=process.env.VAPID_PUBLIC_KEY,PRIVATE_KEY=process.env.VAPID_PRIVATE_KEY,CONTACT=process.env.VAPID_CONTACT||"mailto:preppulse@example.com";
if(!PUBLIC_KEY||!PRIVATE_KEY)console.warn("VAPID_PUBLIC_KEY/VAPID_PRIVATE_KEY are not configured.");else webpush.setVapidDetails(CONTACT,PUBLIC_KEY,PRIVATE_KEY);
async function readSubs(){try{return JSON.parse(await fs.readFile(DATA_FILE,"utf8"))}catch{return []}}
async function writeSubs(items){await fs.mkdir(DATA_DIR,{recursive:true});await fs.writeFile(DATA_FILE,JSON.stringify(items,null,2))}
app.get("/health",(_,res)=>res.json({ok:true,service:"PrepPulse notifications",timezone:TIMEZONE}));
app.get("/api/config",(_,res)=>res.json({publicKey:PUBLIC_KEY||null}));
app.post("/api/subscribe",async(req,res)=>{try{const {subscription,times={morning:"04:00",evening:"17:30",night:"21:30"}}=req.body||{};if(!subscription?.endpoint)return res.status(400).json({error:"subscription required"});if(!PUBLIC_KEY||!PRIVATE_KEY)return res.status(503).json({error:"Push service is not configured"});const subs=await readSubs();const existing=subs.find(s=>s.subscription.endpoint===subscription.endpoint);const item={subscription,times,updatedAt:new Date().toISOString()};if(existing)Object.assign(existing,item);else subs.push(item);await writeSubs(subs);res.json({ok:true})}catch(err){console.error("Subscribe error:",err);res.status(500).json({error:"Could not save push subscription"})}});
app.post("/api/unsubscribe",async(req,res)=>{const endpoint=req.body?.endpoint;if(!endpoint)return res.status(400).json({error:"endpoint required"});const subs=(await readSubs()).filter(s=>s.subscription.endpoint!==endpoint);await writeSubs(subs);res.json({ok:true})});
app.post("/api/test",async(req,res)=>{try{if(!PUBLIC_KEY||!PRIVATE_KEY)return res.status(503).json({error:"Push service is not configured"});const endpoint=req.body?.endpoint;if(!endpoint)return res.status(400).json({error:"endpoint required"});const sub=(await readSubs()).find(s=>s.subscription.endpoint===endpoint);if(!sub)return res.status(404).json({error:"subscription not found. Enable mobile push again."});const sent=await send(sub,{title:"PrepPulse test",body:"Mobile push notifications are working.",url:"/"});if(!sent)return res.status(502).json({error:"Push provider rejected the subscription. Tap Enable mobile push again to create a fresh subscription."});res.json({ok:true})}catch(err){console.error("Test notification error:",err);res.status(500).json({error:"Test notification failed on the notification server."})}});
async function send(item,payload){try{await webpush.sendNotification(item.subscription,JSON.stringify(payload));return true}catch(err){console.error("Push error:",err.statusCode||"",err.message);if(err.statusCode===404||err.statusCode===410){const subs=await readSubs();await writeSubs(subs.filter(s=>s.subscription.endpoint!==item.subscription.endpoint))}return false}}
function currentTimeParts(){const parts=new Intl.DateTimeFormat("en-GB",{timeZone:TIMEZONE,hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date());return {hour:parts.find(p=>p.type==="hour")?.value,minute:parts.find(p=>p.type==="minute")?.value}}
cron.schedule("* * * * *",async()=>{const {hour,minute}=currentTimeParts(),now=`${hour}:${minute}`;const subs=await readSubs();for(const item of subs){for(const [kind,time] of Object.entries(item.times||{})){if(time!==now)continue;const messages={morning:["Good morning — GATE 2027","Get up, drink water, and start today's planned study session."],evening:["PrepPulse evening check-in","Start your second GATE study session now."],night:["PrepPulse night review","Close the day, update progress, and review your mistakes."]};const [title,body]=messages[kind]||["PrepPulse","Time for your study session."];await send(item,{title,body,url:"/"})}}},{timezone:TIMEZONE});
app.listen(PORT,"0.0.0.0",()=>console.log(`PrepPulse notification server running on ${PORT} in ${TIMEZONE}`));